package Exception;

public class OneTryMultipleCatch 
{

	public static void main(String[] args) 
	{
		int ar[] = new int[4];
		int i,j,k=0;
		i = 8;
		j = 0;
		
		try
		{
			
			k = i/j;
			for(int c=0;i<=4;i++)
			{
				ar[c] = c+1;
			}
			
			for(int value : ar)
			{
				System.out.println(value);
			}
		}
		catch(ArithmeticException e)
		{
//			System.out.println(e);
			System.out.println("Cannot devide by Zero "+ e);
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			System.out.println(e);
		}
		System.out.println(k);
	}

}
